### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by thewebbeckons** [SheikhElMoctarG/shortly-link#1]
Hey, 

Just wanted to mention (caught your post on linkedin), that seems like some dark mode stylings are a bit off in your project. When I view it from chrome I'm seeing this. 

![image](https://github.com/SheikhElMoctarG/shortly-link/assets/3504767/17c5c6e9-540f-437d-9972-1b46c528faf1)

**Comment by SheikhElMoctarG** [comment]
I debugged the project in chrome and other browsers, but didnt see this problem
can u debug it and make it pull request?

**Comment by thewebbeckons** [comment]
Hey,

So tried to isolate what was happening and it looks like it was on my end; some chrome extension was injecting a .dark body background color (not even sure which) so can close this out. Sorry for the inconvenience.
